ConcurrentWitness2Test/start.sh svcomp23-witness-benchmarks/tools/lf-checker/ldv-races/race-3_2-container_of-global.yml/race-3_2-container_of-global.i --graphml-witness svcomp23-witness-benchmarks/tools/lf-checker/ldv-races/race-3_2-container_of-global.yml/witness.graphml


--------------------------------------------------------------------------------


Traceback (most recent call last):
  File "/home/runner/work/ConcurrentWitness2Test/ConcurrentWitness2Test/ConcurrentWitness2Test/main.py", line 88, in translate_to_c
    result = subprocess.run([bin_name], capture_output=True, text=True)
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1796, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
BlockingIOError: [Errno 11] Resource temporarily unavailable
/tmp/BenchExec_run_bhc2ckxe/tmp/tmp0t470o4p.c
Compilation started
Compilation ended (exit code 0)
Execution started
Execution ended (exit code -11)
Execution started
Execution ended (exit code -11)
Execution started
Execution ended (exit code -11)
Execution started
Execution ended (exit code -11)
Execution started
Execution ended (exit code -11)
Execution started
Execution ended (exit code -11)
Execution started
Execution ended (exit code -11)
Execution started
Execution ended (exit code -11)
Execution started
Execution ended (exit code -11)
Execution started
Execution ended (exit code -11)
Execution started
Execution ended (exit code -11)
Execution started
Execution ended (exit code -11)
Execution started
Execution ended (exit code -11)
Execution started
Execution ended (exit code -11)
Execution started
Execution ended (exit code -11)
Execution started
Execution ended (exit code -11)
Execution started
Execution ended (exit code -11)
Execution started
Execution ended (exit code -11)
Execution started
Execution ended (exit code -11)
Execution started
Execution ended (exit code -11)
Execution started
Execution ended (exit code -11)
Execution started
Execution ended (exit code -11)
Execution started
Execution ended (exit code -11)
Execution started
Execution ended (exit code -11)
Execution started
Execution ended (exit code -11)
Execution started
Execution ended (exit code -11)
Execution started
Execution ended (exit code -11)
Execution started
Execution ended (exit code -11)
Execution started
Execution ended (exit code -11)
Execution started
Execution ended (exit code -11)
Execution started
Execution ended (exit code -11)
Execution started
Execution ended (exit code -11)
Execution started
Execution ended (exit code -11)
Execution started
Execution ended (exit code -11)
Execution started
Execution ended (exit code -11)
Execution started
Execution ended (exit code -11)
Execution started
Execution ended (exit code -11)
Execution started
Execution ended (exit code -11)
Execution started
Execution ended (exit code -11)
Execution started
Execution ended (exit code -11)
Execution started
Execution ended (exit code -11)
Execution started
Execution ended (exit code -11)
Execution started
Execution ended (exit code -11)
Execution started
Execution ended (exit code -11)
Execution started
Execution ended (exit code -11)
Execution started
Execution ended (exit code -11)
Execution started
Execution ended (exit code -11)
Execution started
Execution ended (exit code -11)
Execution started
Execution ended (exit code -11)
Execution started
Execution ended (exit code -11)
Execution started
Execution ended (exit code -11)
Execution started
Execution ended (exit code -11)
Execution started
Execution ended (exit code -11)
Execution started
Execution ended (exit code -11)
Execution started
Execution ended (exit code -11)
Execution started
Reached error!

Execution ended (exit code 74)
Verdict: Unknown error
