ConcurrentWitness2Test/start.sh svcomp23-witness-benchmarks/tools/esbmc-incr/goblint-regression/13-privatized_18-first-reads_unknown_2_pos.yml/13-privatized_18-first-reads_unknown_2_pos.i --graphml-witness svcomp23-witness-benchmarks/tools/esbmc-incr/goblint-regression/13-privatized_18-first-reads_unknown_2_pos.yml/witness.graphml


--------------------------------------------------------------------------------


Traceback (most recent call last):
  File "/home/runner/work/ConcurrentWitness2Test/ConcurrentWitness2Test/ConcurrentWitness2Test/main.py", line 57, in translate_to_c
    reach_error(ast)
  File "/home/runner/work/ConcurrentWitness2Test/ConcurrentWitness2Test/ConcurrentWitness2Test/tweaks.py", line 24, in reach_error
    extern_decl = Decl(
                  ^^^^^
TypeError: Decl.__init__() missing 1 required positional argument: 'align'
Verdict: Unknown error
