ConcurrentWitness2Test/start.sh svcomp23-witness-benchmarks/tools/coveriteam-verifier-parallel-portfolio/pthread-wmm/rfi007_power.oepc_power.opt_pso.oepc_pso.opt_rmo.oepc_rmo.opt.yml/rfi007_power.oepc_power.opt_pso.oepc_pso.opt_rmo.oepc_rmo.opt.i --graphml-witness svcomp23-witness-benchmarks/tools/coveriteam-verifier-parallel-portfolio/pthread-wmm/rfi007_power.oepc_power.opt_pso.oepc_pso.opt_rmo.oepc_rmo.opt.yml/witness.graphml


--------------------------------------------------------------------------------


Traceback (most recent call last):
  File "/home/runner/work/ConcurrentWitness2Test/ConcurrentWitness2Test/ConcurrentWitness2Test/main.py", line 57, in translate_to_c
    reach_error(ast)
  File "/home/runner/work/ConcurrentWitness2Test/ConcurrentWitness2Test/ConcurrentWitness2Test/tweaks.py", line 24, in reach_error
    extern_decl = Decl(
                  ^^^^^
TypeError: Decl.__init__() missing 1 required positional argument: 'align'
Verdict: Unknown error
